### ISSUE TITLE
ScriptDom can't parse CREATE DATABASE ... ELASTIC_POOL

### ISSUE THREAD

**Issue by taspeotis** [microsoft/SqlScriptDOM#23]
ScriptDom doesn't understand SQL Azure Elastic Pools.

- SqlPackage or DacFx Version: 160.5400.1
- .NET Framework (Windows-only) or .NET Core: 6.0.101
- Environment (local platform and source/target platforms): SQL Azure

**Steps to Reproduce:**

You can take [this example `CREATE DATABASE` statement from the documentation](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-database-transact-sql?view=azuresqldb-current&preserve-view=true&tabs=sqlpool#create-a-database-in-an-elastic-pool) for reproduction:

```cs
const string sql = "CREATE DATABASE db1 ( SERVICE_OBJECTIVE = ELASTIC_POOL ( name = S3M100 ) ) ;";
using var stringReader = new StringReader(sql);
var parser = new TSql160Parser(true, SqlEngineType.All);
var fragment = parser.Parse(stringReader, out var errors);
```

`errors` now contains one error: `Incorrect syntax near ELASTIC_POOL`. I tried `SqlEngineType.SqlAzure` but the result was the same.

SQL Azure parses it:

![image](https://user-images.githubusercontent.com/1189399/154840214-e93115de-cacd-46d0-a420-c40383d0c93c.png)

And if I try to execute it, it runs.

**Comment by arvindshmicrosoft** [comment]
I'm currently working on a PR to address this.
