### ISSUE TITLE
DacFx: Cannot include $node_id in an index

### ISSUE THREAD

**Issue by JerryNixon** [microsoft/SqlScriptDOM#25]
- DacFx Version: SQL Server Data Tools 17.0.62203.25080
- Environment: VisualStudio.17.Release/17.1.3+32328.378, Windows 11

## Problem:

This syntax is invalid in Visual Studio right now. 
(_Note: this syntax is valid and works in SSMS just fine._ )
````SQL
CREATE INDEX IDX_MYINDEX
	ON graph.MYNODE (Column1) INCLUDE ($node_id)
````

Resulting error:
![image](https://user-images.githubusercontent.com/1749983/166557937-21951595-01e2-4bb2-b875-5a90807aa2c3.png)

This syntax, however, is not invalid in Visual Studio right now.
````SQL
CREATE INDEX IDX_MYINDEX 
        ON graph.MYNODE ($node_id) INCLUDE (Column1)
````

Workaround: Run as string using `EXEC(@SQL)` in POSTPUBLISH script. Like this:
````SQL
DECLARE @SQL VARCHAR(MAX) = '
IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = ''IDX_MYINDEX'')
CRCREATE INDEX IDX_MYINDEX
	ON graph.MYNODE (Column1) INCLUDE ($node_id)'
EXEC(@SQL)
````

**Comment by arvindshmicrosoft** [comment]
@llali @barbaravaldez kindly assign this as well to me. I have a fix well under way.

**Comment by llali** [comment]
> @llali @barbaravaldez kindly assign this as well to me. I have a fix well under way.

Thanks! items assigned.
