### ISSUE TITLE
Incorrect Syntax near URL in Restore Database statement

### ISSUE THREAD

**Issue by SeenaAugusty** [microsoft/SqlScriptDOM#29]
- SqlPackage or DacFx Version: 
- .NET Framework (Windows-only) or .NET Core: 
- Environment (local platform and source/target platforms):

**Steps to Reproduce:**

1. Try to build a statement in VS that has Restore Database with URL then it will shows the below syntax error from ScriptDom Parser![image](https://user-images.githubusercontent.com/113181575/203305924-1250fd58-adb8-48b0-a3c6-1e65dc80a52e.png)
**Did this occur in prior versions?  If not - which version(s) did it work in?** Yes

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by DannyvB** [comment]
@SeenaAugusty to which version do I need to upgrade to use it now?
