### ISSUE TITLE
No solution file?

### ISSUE THREAD

**Issue by clement911** [microsoft/SqlScriptDOM#34]
Is it expected that the repo contains no .sln file?
I tried opening Microsoft.SqlServer.TransactSql.ScriptDom.csproj directly but it crashes VS 2022

**Comment by barbaravaldez** [comment]
Hi @clement911, we actually use SlnGen to generate the Visual Studio sln.
Here are the instructions:
https://github.com/microsoft/SqlScriptDOM/blob/main/CONTRIBUTING.md#getting-started

**Comment by clement911** [comment]
gotcha. sorry I missed that!
Will give it a try...
