### ISSUE TITLE
ScriptGeneratorOption.SqlVersion is always Sql90 even if we have different SqlScriptGenerator

### ISSUE THREAD

**Issue by Phantom-Sixth-Man** [microsoft/SqlScriptDOM#64]
ScriptGeneratorOption.SqlVersion is always Sql90 even if we have different SqlScriptGenerator

![image](https://github.com/microsoft/SqlScriptDOM/assets/30655124/383a6683-d1fb-4e32-8cfb-7af5babb7342)

**Comment by SeenaAugusty** [comment]
Hi @Phantom-Sixth-Man Could you share the steps to repro this issue?

**Comment by Phantom-Sixth-Man** [comment]
Hello @SeenaAugusty, I have opened a PR - https://github.com/microsoft/SqlScriptDOM/pull/67.
Please review and merge.

**Comment by SeenaAugusty** [comment]
It is fixed in this PR https://github.com/microsoft/SqlScriptDOM/pull/67
